name: Endpoint Health Monitor

on:
#   schedule:
#     - cron: '*/5 * * * *' # Every 5Min, stops after a minute
  workflow_dispatch:
  


jobs:
  run-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run health monitor
        run: |

          go run main.go endpoint.yaml

    #   - name: Upload health log
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: health-log
    #       path: endpoint-health.txt